apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/part-of: data-platform
type: Opaque
stringData:
  webserver-secret-key: "bWVnYS1zZWNyZXQta2V5LWZvci1haXJmbG93LWxvY2FsLWRldmVsb3BtZW50"
  fernet-key: "tYq7l1j7jW2s4Z8z1k6L2x8Q4w9E7r3T1y5U6i8O0p4="
  sql-alchemy-conn: "postgresql+psycopg2://airflow:airflow123@postgres.postgres.svc.cluster.local:5432/airflow"
  admin-password: "admin"
  aws-access-key-id: "admin"
  aws-secret-access-key: "password123"
  # Pre-configured Connections via Secrets
  AIRFLOW_CONN_AWS_S3_MINIO: "aws://admin:password123@/?endpoint_url=http%3A%2F%2Fminio.minio.svc.cluster.local%3A9000&region_name=us-east-1"
  AIRFLOW_CONN_POSTGRES_BANKING: "postgresql://postgres:postgres123@postgres.postgres.svc.cluster.local:5432/banking"
  AIRFLOW_CONN_POSTGRES_DEFAULT: "postgresql://postgres:postgres123@postgres.postgres.svc.cluster.local:5432/banking"
