apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: postgres
type: Opaque
stringData:
  postgres-password: "postgres123"
  metastore-password: "metastore123"
  airflow-password: "airflow123"
  superset-password: "superset123"
