apiVersion: v1
kind: Service
metadata:
  name: gravitino
  namespace: gravitino
  labels:
    app: gravitino
spec:
  type: LoadBalancer
  selector:
    app: gravitino
  ports:
    - name: web-rest
      port: 8090
      targetPort: 8090
    - name: iceberg-rest
      port: 9001
      targetPort: 9001
