apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secrets
  namespace: clickhouse
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: data-platform
type: Opaque
stringData:
  admin-user: "admin"
  admin-password: "clickhouse123"
