apiVersion: v1
kind: Secret
metadata:
  name: superset-secrets
  namespace: superset
type: Opaque
stringData:
  secret-key: "bWVnYS1zZWNyZXQta2V5LWZvci1zdXBlcnNldC1sb2NhbC1kZXZlbG9wbWVudA=="
  sqlalchemy-uri: "postgresql://superset:superset123@postgres.postgres.svc.cluster.local:5432/superset"
  admin-password: "admin"
